### ISSUE TITLE
Python3 compatibility

### ISSUE THREAD

**Issue by DirectorX** [alephsecurity/xnu-qemu-arm64-tools#12]
Python 2 is discontinued now, please support python3

**Comment by jonyafek** [comment]
The only python script currently w/o support for python3 is decompress_lzss.py which was found online and imported into the project. This is an open source implementation of decompression of the lzss algorithm. I would love to have this ported to python3 but for now with our limited resources we couldn't prioritize working on this. PRs are welcome :) In the meanwhile, other open source c implementations can be used or any other implementation available online or other wise.
