### ISSUE TITLE
nm: kernelcache.release.n66.out: file format not recognized

### ISSUE THREAD

**Issue by dky4** [alephsecurity/xnu-qemu-arm64-tools#20]
When I was doing this https://github.com/alephsecurity/xnu-qemu-arm64-tools/tree/master/aleph_bdev_drv in the guide there was to do nm kernelcache.release.n66.out > symbols.nm, and when i did that, i got
nm: kernelcache.release.n66.out: file format not recognized. Is this supposed to happen or is this a problem? I am doing this on Linux if you need to know

**Comment by Ian321** [comment]
Have you tried `llvm-nm` ?

**Comment by sickcodes** [comment]
Here's a full list of commands I used to build it:

https://github.com/sickcodes/Docker-eyeOS/blob/master/osx-build-xnu-disks.sh#L132

**Comment by dky4** [comment]
i just found out i asked this after getting the same error 1 year later. i used `llvm-nm` and it worked
