### ISSUE TITLE
[GHIDRA] Reconstructing C++ classes in the iOS kernelcache using Ghidra

### ISSUE THREAD

**Issue by V3rochka** [alephsecurity/xnu-qemu-arm64-tools#4]
### Description
Following the great work by  Brandon Azad, we want to implement this functionality in Ghidra.
### Resources 
[Brandon's Blog](https://bazad.github.io/2018/03/ida-kernelcache-class-reconstruction)

**Comment by R3n3r0** [comment]
This script exist in https://github.com/0x36/ghidra_kernelcache

**Comment by V3rochka** [comment]
Closing the issue thanks to @R3n3r0 's comment.
